chore: Ensure that action code is built

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -83,8 +83,36 @@ jobs:
       # workflow artifact.
       - if: ${{ failure() && steps.diff.outcome == 'failure' }}
         name: Upload Artifact
-        id: upload
+        id: upload-dist
         uses: actions/upload-artifact@v4
         with:
           name: dist
           path: dist/
+
+      # This will fail the workflow if the `dist-action/` directory is different than
+      # expected.
+      - name: Compare Directories
+        id: diff-action
+        run: |
+          if [ ! -d dist-action/ ]; then
+            echo "Expected dist-action/ directory does not exist.  See status below:"
+            ls -la ./
+            exit 1
+          fi
+          if [ "$(git diff --ignore-space-at-eol --text dist-action/ | wc -l)" -gt "0" ]; then
+            echo "Detected uncommitted changes after build. See status below:"
+            git diff --ignore-space-at-eol --text dist-action/
+            exit 1
+          fi
+
+      # If `dist-action/` was different than expected, upload the expected version as a
+      # workflow artifact.
+      - if: ${{ failure() && steps.diff-action.outcome == 'failure' }}
+        name: Upload Artifact
+        id: upload-dist-action
+        uses: actions/upload-artifact@v4
+        with:
+          name: dist-action
+          path: dist-action/
+
+      
